#!/bin/bash

# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.


if [ ! -d "${OPENSHIFT_REPO_DIR}uploads" ]; then
  mkdir -p ${OPENSHIFT_REPO_DIR}uploads
  cp -rf ${OPENSHIFT_REPO_DIR}uploads/* ${OPENSHIFT_DATA_DIR}uploads/
fi

if [ -d ${OPENSHIFT_REPO_DIR}uploads ]; then
  rm -rf ${OPENSHIFT_REPO_DIR}uploads
fi
if [ ! -d ${OPENSHIFT_DATA_DIR}uploads ]; then
    mkdir ${OPENSHIFT_DATA_DIR}uploads
fi
ln -sf ${OPENSHIFT_DATA_DIR}uploads ${OPENSHIFT_REPO_DIR}uploads
cp -rf ${OPENSHIFT_REPO_DIR}uploads/* ${OPENSHIFT_DATA_DIR}uploads/ 2>/dev/null
